name: 'Get and Cached Deps'
description: 'Get deps and Cached them'
inputs:
  caching:
    description: 'Whether to cache dep'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        if: inputs.caching =='true'
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true' || input.caching != 'true'
        run: npm ci
        shell: bash